name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    name: Node
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - name: Use Node 24 and pnpm
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Site
        run: pnpm run build:site
